version : '3.8'

services:
    postgres_db:
        build:
            context: .
            dockerfile: pgdb.Dockerfile
        restart: always
        container_name: postgres_db
        privileged: true
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
            - PGDATA=/var/lib/postgresql/data
        user: root
        ports:
            - "5432:5432"
        volumes:
            - ./database/dbdata:/var/lib/postgresql/data
    python_app:
        build:
            context: .
            dockerfile: python.Dockerfile
        container_name: python_app
        user: root
        volumes:
            - ./:/app
        entrypoint: watchmedo auto-restart --recursive --pattern="*.py,*.txt,*.csv,*.xlsx,*.css,*.png,*.jpg,*.js" --directory="." python ./app.py
        ports:
            - "80:80"
